version: '3.8'
services:
  server:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - FFMPEG_BINARY=/usr/bin/ffmpeg
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs